### ISSUE TITLE
r studio not working on c4-raleighlab1 node

### ISSUE THREAD

**Issue by Aggarwal-Ayush** [UCSF-CBI/rstudio-server-controller#106]
Hi 
It's been a while since the r studio server stopped working on the c4-raleighlab1 node (after the c4 update). Below is the list of commands and error that I'm getting:

`[ayaggarwal@c4-raleighlab1 ~]$ module load CBI r hdf5 rstudio-server-controller miniconda3 jags
[ayaggarwal@c4-raleighlab1 ~]$ rsc start
WARNING: Detected ./.RData [2595 bytes]. It will be loaded by R during startup. If this file is very large, R might fail to launch.
rserver: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
ERROR: It looks like the RStudio Server failed during launch ['rserver' process (PID 0 on c4-raleighlab1) no longer exists; attempted to use TCP port 14002, which is available]. This happened with rsc 0.16.0 [running on c4-raleighlab1], RStudio Server 2023.12.0-369 (Ocean Storm) for Linux [/software/c4/cbi/software/rstudio-server-2023.12.0-369/bin/rstudio-server], and R 4.4.1 (2024-06-14) -- "Race for Your Life" [/software/c4/cbi/software/_rocky8/R-4.4.1-gcc13/bin/R].
Traceback:
1: rsc_error() on line #126 in /software/c4/cbi/software/rstudio-server-controller-0.16.0/bin/rsc
2: assert_rserver_running() on line #976 in /software/c4/cbi/software/rstudio-server-controller-0.16.0/bin/rsc
3: main() on line #1929 in /software/c4/cbi/software/rstudio-server-controller-0.16.0/bin/rsc
Exiting (exit 1)
Shutting down RStudio Server ...
Shutting down RStudio Server ... done`

Any help with this is much appreciated!! @HenrikBengtsson @dstyrk-ucsf 
PS It's working on c4-dev1 so this is specific to c4-raleighlab1 node.

Thanks!!

**Comment by HenrikBengtsson** [comment]
This is a C4 specific issue; please use https://github.com/UCSF-CBI/c4-help/issues for such problems.
