### ISSUE TITLE
Interactive Jobs Not Working

### ISSUE THREAD

**Issue by ggruenhagen3** [UCSF-CBI/rstudio-server-controller#107]
Requesting an interactive job using srun is causing the terminal to hang and become unresponsive. Using CTRL+C does not work to stop the request and hitting ENTER does not produce a new line. After ~5+ minutes, I get a message like this:
```
srun: error: timeout waiting for task launch, started 0 of 1 tasks
srun: launch/slurm: launch_p_step_launch: StepId=35906.0 aborted before step completely launched.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete
```

Expected behavior: a message that resources have been requested and then allocated, with the ability to stop this process at any point with CTRL+C
Username: `ggruenh`
Commands Tried: `srun --partition=freecycle --nodes=1 --cpus-per-task=12 --mem=100G --time=9:00:00 --pty $SHELL` and `srun --nodes=1 --cpus-per-task=6 --mem=1G --time=00:02:00 --pty $SHELL`

PS. The main issue isn't that I can't cancel an interactive job, it's that **they are not working** at the moment.

**Comment by HenrikBengtsson** [comment]
I see you re-posted at the C4-help issue tracker; that's a much better place, because this question seems to specific to that HPC environment
