### ISSUE TITLE
Validate that the EXIT trap by `rsc start` is trigger when a Slurm job is cancelled

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/rstudio-server-controller#21]
This validation task stems from https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/issues/2#issuecomment-1023664077.

**Comment by HenrikBengtsson** [comment]
EXIT traps are probably _not_ triggered by `kill -9` (`SIGKILL`). So, if that's what's signaled, the rsc internal cleanup process might be skipped.

Task:

* [ ] Identify which signals Slurm uses to cancel a job and trap those. It might send multiple ones, e.g. first a nice one (e.g. SIGUSR1, INT, or TERM) and then a full on KILL some seconds later if process is still running.

/cc @hgputnam

**Comment by HenrikBengtsson** [comment]
From `man scancel`:

```
To  cancel  a job, invoke scancel without --signal option.  This will send first a SIGCONT to all steps to
       eventually wake them up followed by a SIGTERM, then wait the KillWait duration defined in  the  slurm.conf
       file  and finally if they have not terminated send a SIGKILL.  This gives time for the running job/step(s)
       to clean up.
```

We have:

```sh
[henrik@c4-log1 ~]$ grep KillWait /etc/slurm/slurm.conf
KillWait=30
```

which I'd expect to mean that SIGKILL is signalled 30 seconds after SIGTERM.

**Comment by hgputnam** [comment]
We might be able to control that somewhat. There is a file in each app responsible for the job submission on our scheduler: submit.yml.erb We might be able to add options to scancel there, I will look into it.

**Comment by HenrikBengtsson** [comment]
Tests with:

```sh
$ sbatch --mem=10M --time=00:01:00 traps.sh
```

confirms that after 63 seconds, SIGTERM (=15) and SIGCONT (=18) are signalled, because we surpass the maximum run-time.  Then, after 30 seconds, the process is SIGKILL:ed (=9), which is a signal that cannot be caught.  Importantly, these tests show that the EXIT trap (trap ... 0) is never triggered.  That is only triggered when the script exits, but neither SIGTERM nor SIGCONT achieves that.  Only SIGKILL terminates the process, but that signal cannot be captured.


# Job cancelled when running out run-time

```sh
$ cat slurm-406325.out
$ cat slurm-406325.out
[2022-01-27 16:12:24-08:00] Started
PID: 25382
[2022-01-27 16:12:24-08:00] Creating traps ...
[2022-01-27 16:12:24-08:00] Waiting ...
...............................................................slurmstepd: error: *** JOB 406325 ON c4-n12 CANCELLED AT 2022-01-27T16:13:27 DUE TO TIME LIMIT ***

[2022-01-27 16:13:28-08:00] received signal 15

[2022-01-27 16:13:28-08:00] received signal 18
..............................
```
There are 30 `.`:s at the end, corresponding to 30 seconds, before the process is terminated.


# Job cancelled by user

Using

```sh
$ scanel 406324
```

results in the same signals being signalled:

```sh
$ cat slurm-406324.out
[2022-01-27 16:12:21-08:00] Started
PID: 25355
[2022-01-27 16:12:21-08:00] Creating traps ...
[2022-01-27 16:12:21-08:00] Waiting ...
............slurmstepd: error: *** JOB 406324 ON c4-n12 CANCELLED AT 2022-01-27T16:12:33 ***

[2022-01-27 16:12:34-08:00] received signal 15

[2022-01-27 16:12:34-08:00] received signal 18
.............................
```

# The test script
```sh
$ cat traps.sh
#! /usr/bin/env bash

printf "[%s] Started\n" "$(date --rfc-3339=seconds)"
echo "PID: $$"

printf "[%s] Creating traps ...\n" "$(date --rfc-3339=seconds)"
function on_trap {
    printf "\n[%s] received signal %d\n" "$(date --rfc-3339=seconds)" "${1:?}"
}
for kk in {0..64}; do
    trap "on_trap ${kk}" "${kk}"
done

printf "[%s] Waiting ...\n" "$(date --rfc-3339=seconds)"
while true; do
    printf "."
    sleep 1
done

printf "[%s] Exiting!\n" "$(date --rfc-3339=seconds)"
```

**Comment by HenrikBengtsson** [comment]
Thus, in addition to `EXIT`, which is triggered by SIGINT (=2) for user hitting <kbd>Ctrl-C</kbd> in interactive mode, `rsc` should listen to `SIGTERM (=15)`.

**Comment by HenrikBengtsson** [comment]
I've updated `rsc start` to have a trap also for `SIGTERM`.  I've verified that it works when I do a `kill -SIGTERM <pid>`.  However, for some reason I cannot get `scancel <jobid>` and Slurm to signal SIGTERM and SIGCONT to the `rsc` script, despite it works with the above `traps.sh` script.  Hmm...
