### ISSUE TITLE
ssh tunnel directions fail on Mac OSX

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/rstudio-server-controller#30]
Not exactly sure why yet. Following the rsc suggestion:
```
harryputnam@CC-D17LVCG-LT ~ % ssh -J hputnam@c4-log2 -L 8787:c4-n12:43242 c4-n12
harryputnam@c4-n12's password: 
Permission denied, please try again.
harryputnam@c4-n12's password: 
```
It did not accept my password. This syntax does work on my Mac:
`ssh -N -L 8787:c4-n12:43242 hputnam@c4-log2  `

**Comment by hgputnam** [comment]
Researching...

**Comment by HenrikBengtsson** [comment]
Suggestion: troubleshoot without the port forwarding.

It might have to do with SSH key agent forwarding.

**Comment by hgputnam** [comment]
According to `man ssh` on my Mac, the -J should work. However online examples I have looked at all use the other syntax: `ssh -N -L 8787:c4-n12:43242 hputnam@c4-log2`

Not sure why no one uses the -J option other than it breaks on Macs. Examples:

https://www.studytonight.com/post/how-to-setup-ssh-tunneling-in-mac-os-or-ubuntu
https://helpdesk.eoas.ubc.ca/kb/articles/how-to-ssh-tunnel-a-connection-using-macos

Is it possible to add a "for macs do this" line to the output?

**Comment by HenrikBengtsson** [comment]
Yes, we can adjust the instructions by `rsc`.  FYI, I dropped the ssh `-N`, because it's always nice to be able to re-use that login for other things.

**Comment by HenrikBengtsson** [comment]
Honestly, I don't know what I was thinking when I introduced `-J`. I've updated the instruction to use:

```sh
ssh -L 8787:c4-n12:43242 alice@c4-log1.ucsf.edu
```

**Comment by HenrikBengtsson** [comment]
> ... without the -N. We just get a terminal on the login node...

What's the problem with that?  Why is it "required for Macs"?

 With and without `ssh -N ...`, we end up needing a new terminal. I figured it's better to put that terminal in use, so I decided to go without the `-N`. What am I missing?

**Comment by hgputnam** [comment]
Not what people expect, they have been doing this following online tutorials which invariable use -N. I think the guy was just confused, the tunnel was probably there...

**Comment by hgputnam** [comment]
You are not going to believe this. The user tells me that the -N did not work for him. He put in a -J (aka what you had before) and it worked for him. I just asked him what OSX version he is on. UCSF just released the newest major OS X release for UCSF laptops so he could well be on a newer version than me...

**Comment by hgputnam** [comment]
The guy is on an older version than me. Yeah, let's go slow with this. I voter for leaving it as-is for now. 

Reverse tunnels can be dangerous I had to react to a really bad virus at EBMUD that took down all our mail servers and quite a bit of the Windows infrastructure. The virus got in via a persistent reverse tunnel between an EBMUD workstation and the user's Home consumer wifi router. I think one of his kids got it on the family computer and it wormed into EBMUD via that tunnel. The user was our CIO so I couldn't even yell at him...

**Comment by HenrikBengtsson** [comment]
> The user was our CIO so I couldn't even yell at him...

... but now you told the world ;) [you can delete comments here if you want]

**Comment by HenrikBengtsson** [comment]
I've updated the README with instructions on how to run and access `rsc` running on a remote machine.
