### ISSUE TITLE
Getting new errors when rsc is run from srun

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/rstudio-server-controller#32]
I only see this from an srun session, not on a native session on a dev node:

```
hputnam@c4-dev3 ~]$ srun --pty --mem 32g --ntasks 4 --time 0-08:00 --gres=scratch:20g $SHELL
srun: job 419492 queued and waiting for resources
srun: job 419492 has been allocated resources
[hputnam@c4-n3:job=419492 ~]$ module load CBI rstudio-server-controller
[hputnam@c4-n3:job=419492 ~]$ rsc start port=uid
mktemp: failed to create file via template ‘/scratch/hputnam/419492/tmp.XXXXXXXXXX’: No such file or directory
/software/c4/cbi/software/rstudio-server-controller-0.3.4/bin/rsc: line 506: : No such file or directory
grep: : No such file or directory
mv: cannot move ‘.tmp’ to ‘’: No such file or directory
mv: cannot stat ‘’: No such file or directory
hputnam, your personal RStudio Server is available on <http://c4-n3:8787>. If you are running from a remote machine without direct access to c4-n3, you can use SSH port forwarding to access the RStudio Server at <http://127.0.0.1:8787> by running 'ssh -L 8787:c4-n3:8787 hputnam@<login-machine>' in a second terminal. Any R session started times out after being idle for 480 minutes.
```
rsc does eventually launch. This could be because srun & sbatch use different pro/epilog scripts. Looking into that...

**Comment by hgputnam** [comment]
Those are commented out in /etc/slurm/slurm.conf:
```
#Prolog=/opt/slurm/prolog.bash
#PrologFlags=Alloc,NoHold
#Epilog=/opt/slurm/epilog.bash
#SrunProlog=/opt/slurm/srun_prolog
#SrunEpilog=/opt/slurm/srun_epilog
TaskProlog=/opt/slurm/task_prolog
TaskEpilog=/opt/slurm/task_epilog
```

**Comment by HenrikBengtsson** [comment]
I rolled out rsc 0.3.4 last night and it did introduce a call to `mktemp`, cf. https://github.com/UCSF-CBI/rstudio-server-controller/blob/6a221e4196400abd22bcb96110ef333d1254117b/bin/rsc#L505

I can work around that `mktemp` (not critical), but, as you've realized, the real problem is that the `TMPDIR` folder is not created by Slurm.

**Comment by hgputnam** [comment]
I FINALLY understand the problem. srun_prolog and srun_epilog execute on the **submit** host NOT the **compute** host. So, very confusing. This is a big help:https://slurm.schedmd.com/prolog_epilog.html

**Comment by HenrikBengtsson** [comment]
Just so you don't forget to undo this; I've been getting:

```sh
[henrik@c4-log1 .local]$ srun --nodes=1 --ntasks=2 --mem=32G --time=03:00:00 --pty $SHELL
srun: job 419881 queued and waiting for resources
srun: job 419881 has been allocated resources
mkdir: cannot create directory ‘/scratch/henrik’: No such file or directory
                                                                           mkdir: cannot create directory ‘/scratch/henrik/419881’: No such file or directory
                                                                                                                                                             export TMPDIR=/scratch/henrik/419881
    [henrik@c4-n3:job=419881 .local]$ 
```

for several hours now. That output (to stdout and stderr) risks breaking existing pipelines.

**Comment by hgputnam** [comment]
I rolled it back. I think this is why I had them commented. The key settings from slurm.conf are:

```
#SrunProlog=/opt/slurm/srun_prolog
#SrunEpilog=/opt/slurm/srun_epilog
```

**Comment by HenrikBengtsson** [comment]
Okay. Slurm has some weird behavior and design.

Next release, rsc 0.3.5, won't use `mktemp` (https://github.com/UCSF-CBI/rstudio-server-controller/commit/031fb22ecde91edb0198195f25d92ff48952c23a).  That'll at least allow us to keep prototyping rsc in interactive Slurm jobs.

Since this is unrelated to `rsc`, let's continue the discussion on `TMPDIR` in another issue tracker.
