### ISSUE TITLE
Stranded rserver processes

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/rstudio-server-controller#53]
One of our C4 users has run into an odd situation where it looks like a couple of rserver processes were stranded. This is on our new c4-raleighlab1 which is setup exactly like c4-dev[1-3] (not an exec node). 

** ps output **
```
$ ps -ef |grep ceaton
root      29706  29532  0 15:36 pts/3    00:00:00 su - ceaton
ceaton    29707  29706  0 15:36 pts/3    00:00:00 -bash
ceaton    30056  29707  0 15:37 pts/3    00:00:00 ps -ef
ceaton    30057  29707  0 15:37 pts/3    00:00:00 grep --color=auto ceaton
ceaton    33171      1  0 Feb24 ?        00:00:43 rserver --config-file=/c4/home/ceaton/.config/rsc/rserver.conf. <<<<<<<<<<<<
ceaton    35526      1  0 Feb24 ?        00:02:16 rserver --config-file=/c4/home/ceaton/.config/rsc/rserver.conf  <<<<<<<<<<<<
```

** try an `rsc status` **
```
$ module load CBI rstudio-server-controller
$ rsc status
rserver: not running
rsession: not running
lock file: does not exist
$ rsc start
ERROR: Not an integer: ERROR: [INTERNAL]: Identified port is not free: 7921
Traceback:
1: find_free_port() on line #81 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/incl/ports.sh
2: make_rserver_conf() on line #329 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/rsc
3: main() on line #1249 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/rsc
Exiting (exit 1)
Traceback:
1: assert_integer() on line #39 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/incl/asserts.sh
2: assert_port() on line #104 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/incl/ports.sh
3: assert_port_free() on line #111 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/incl/ports.sh
4: make_rserver_conf() on line #331 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/rsc
5: main() on line #1249 in /software/c4/cbi/software/rstudio-server-controller-0.6.1/bin/rsc
Exiting (exit 1)
```

** killing the two procs cleared up the issue **
```
$ kill -9 33171 35526
[ceaton@c4-raleighlab1 ~]$ ps -ef |grep ceaton
root      29706  29532  0 15:36 pts/3    00:00:00 su - ceaton
ceaton    29707  29706  0 15:36 pts/3    00:00:00 -bash
ceaton    37292  29707  5 16:31 pts/3    00:00:00 ps -ef
ceaton    37293  29707  0 16:31 pts/3    00:00:00 grep --color=auto ceaton
$ rsc start
WARNING: Detected a stray lock file (/c4/home/ceaton/.config/rsc/pid.lock). This file was removed, because there was no evidence that another instance was running on this system (no PID files for neither 'rserver' nor 'rsession' were found).
ceaton, your personal RStudio Server is available on <http://c4-raleighlab1:11357>. If you are running from a remote machine without direct access to c4-raleighlab1, you can use SSH port forwarding to access the RStudio Server at <http://127.0.0.1:8787> by running 'ssh -L 8787:c4-raleighlab1:11357 ceaton@<login-machine>' in a second terminal.
Any R session started times out after being idle for 120 minutes.


^CReceived a SIGINT signal => exit 0
Shutting down RStudio Server ...
Shutting down RStudio Server ... done
$ rsc stop
RStudio Server stopped
$ rsc status
rserver: not running
rsession: not running
lock file: does not exist
```

**Comment by hgputnam** [comment]
Sequence of events:

- User contacted me and told me there were some standed processes on c4-dev
- I killed those
- User tried on c4-ralaighlab1

As we can see above, the c4-raleighlab1 procs were over a week old. The stray process on c4-dev1 was from today.

I am not exactly sure how this all evolved.

**Comment by HenrikBengtsson** [comment]
Not sure how that could happend.  `rsc status` looks for the PID files for `rserver` (and `rsession`).  If the PID file doesn't exist, then it concludes that `rserver` is _not_ running.  The PID file is created and removed by the `rserver` process itself, i.e. it's nothing that `rsc` does.  The port is clearly still occupied (which we know thanks to `--port=uid` being the default and that it cleared up when you killed the processes), but there is no PID file.   My best guess is that those are processes that only partially shut down.

From here:

https://github.com/UCSF-CBI/rstudio-server-controller/blob/eb7a793151389761e35263011788ad2a61a5b8e8/bin/rsc#L1165-L1178

to here:

https://github.com/UCSF-CBI/rstudio-server-controller/blob/eb7a793151389761e35263011788ad2a61a5b8e8/bin/rsc#L866-L874

to here:

https://github.com/UCSF-CBI/rstudio-server-controller/blob/eb7a793151389761e35263011788ad2a61a5b8e8/bin/rsc#L767-L783

Next time, run `rsc status --debug` to see the internal steps it takes to infer status.  I don't think it would reveal anything extra, but it doesn't hurt to collect as much info as possible when odd things happens.

**Comment by HenrikBengtsson** [comment]
Forgot to say that it also checks if the PID is still running:

https://github.com/UCSF-CBI/rstudio-server-controller/blob/eb7a793151389761e35263011788ad2a61a5b8e8/bin/rsc#L298-L303

using code from here:

https://github.com/UCSF-CBI/rstudio-server-controller/blob/eb7a793151389761e35263011788ad2a61a5b8e8/bin/rsc#L414-L427

So, it really tries hard to validate that an existing PID file is not a stray one, and if it is, then it is removed.  But if there is no PID file, then it just accepts that there is no process, which apparently there can be.  One thing I could add to `rsc status` is to check for any `rserver` processes (with CLI option `--config-file=$HOME/.config/rsc/rserver.conf`) and produce a warning if that doesn't match what it concluded from the PID file inspection.

**Comment by hgputnam** [comment]
Yeah I think this might be an unusual situation, and I couldn't even begin to reproduce it. Just thought I should report it for knowledge. I didn't know about the --debug option, I will definitely be using that.

**Comment by HenrikBengtsson** [comment]
Another thing is that there's `rsc` process running. If it would, then `rsc start` would have produces:

```
ERROR: alice, another RStudio Server session of yours is already running on hb-x1 on this system.
See 'rsc status' for details. Please terminate that first, e.g. call 'rsc stop' from that machine.
As a last resort, call 'pkill rserver; pkill rsession', remove lock file '/home/hb/.config/rsc/pid.lock',
and retry.
```

**Comment by HenrikBengtsson** [comment]
In the next release, we're now checking for stray `rserver` processes before launching a new one.  So, with the above, you would have gotten:

```sh
$ rsc start
ERROR: Even if there are no PID and lock files, there is another rserver process (PID 32094) already
running on this machine (alice-laptop): rserver --config-file=/home/alice/.config/rsc/rserver.conf
$
```

So, if the user reports that error, then it's a better hint than the port being occupied.  It also protects against launching extra `rserver` processing with `--port=random`.

**Comment by HenrikBengtsson** [comment]
In addition to the `rsc start` assertion error, in the next release `rsc status` will produce a warning if it detects there are stray `rserver` processes running _on the current machine_;

```r
$ rsc status
rserver: not running
rsession: not running
lock file: does not exist
WARNING: Even if there are no PID and lock files, there is another rserver process (PID 32094) already
running on this machine (alice-laptop): rserver --config-file=/home/alice/.config/rsc/rserver.conf
$
```
