### ISSUE TITLE
Question - how to delete cached files?

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/rstudio-server-controller#68]
I had a user last week reporting that, after getting the RStudio signon page in their local browser and entering credentials, the screen just sat there for a long time and never showed the actual workspace. I dug around a bit and found that some files get cached under `~/.config/rsc` so I had the user try to `rm ~/.config/rsc/*` which did not help. I was not able to reproduce this problem with my own or a test account. Many other factors might be at work but I was wondering if deleting other folders under .config might be something to ry for this sort of slowness? Or can we delete the whole .config and let rsc start over?

The user did eventually get the workspace after the above deleting but it took over 30 minutes.

**Comment by HenrikBengtsson** [comment]
Calling:

```sh
$ rsc reset
```

will do it.  It's mentioned in `rsc --help`:

```
Usage:
 rsc <command> [options]

Commands:
 start               Start the RStudio Server
 wait                Wait for RStudio Server instance to be available
 stop                Stop the RStudio Server and any R and SSH sessions
 status              Check whether the RStudio Server is running or not
 config              Output configuration details
 reset               Wipe all configuration
 log                 Output rsession log
```

and it's actually been there since day 1 (rsc 0.1.0).
